### ISSUE TITLE
Rounding up/down should be an option, now it just do it automatically

### ISSUE THREAD

**Issue by Sebastp** [domharrington/js-number-abbreviate#13]
tried doing abbreviate(13992, 1) and it returns "14k" where it should be "13.9k"

**Comment by domharrington** [comment]
I think this is expected functionality! See some of [the tests](https://github.com/domharrington/js-number-abbreviate/blob/master/test.js#L13-L14). Anything larger than 13950 gets rounded up:

```js
> abbreviate(13949, 1)
'13.9k'
> abbreviate(13950, 1)
'14k'
```

Would accept a PR to disable rounding, if you're interested! Alternatively, if you want 2 decimal places you could do this:

```js
> abbreviate(13992, 2)
'13.99k'
```
